version: "3.9"

services:
  api:
    build: .
    container_name: "api"
    volumes:
      - ./:/service
    command: "python app/manage.py run-worker runapi"
    depends_on:
      mongo:
        condition: service_healthy
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}

  mongo:
    image: mongo
    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
#      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
#      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
